[package]
name = "trakr-skytrak"
version.workspace = true
edition.workspace = true
license-file.workspace = true
repository.workspace = true

[dependencies]
trakr-core = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
bytes = { workspace = true }
crc = { workspace = true }
if-addrs = { workspace = true }
aes = { workspace = true }
generic-array = "0.14"

[dev-dependencies]
hex = "0.4"
